version: '3.7'

services:
  external_database:
    container_name: external_database
    image: postgres:11.4-alpine
    env_file: postgres.env
    ports: 
      - 5432:5432
    networks:
      - frontend

networks: 
  frontend: